### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by bobuojisann** [bobuojisann/furima-29784#9]
本番環境URL
https://furima-29784.herokuapp.com/
Basic認証のIDとパスワード
ohagi
112911
出品者用のメールアドレスとパスワード
rara@gmail.com
rara11
購入者用のメールアドレスとパスワード
nana@gmail.com
nana11
購入者用カードの番号・期限・セキュリティコード
4242424242424242
12/24
123

**Comment by mo1015** [comment]
谷川さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、商品出品をする際にエラーとなってしまい、再度アクセスができなくなってしまいました。
<img width="661" alt="スクリーンショット 2020-10-11 11 13 02" src="https://user-images.githubusercontent.com/62644781/95668723-c3ae5b00-0bb2-11eb-80df-6c87e8ced6b0.png">


修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
